version: 0.0
os: linux

files:
  - source: /target/secretsanta-0.0.1-SNAPSHOT.war
    destination: /home/ec2-user/secretsanta/apache-tomcat-9.0.71/webapps
    overwrite: true

permissions:
  - object: /
    pattern: "**"
    mode: 755
    owner: tomcat
    group: tomcat

hooks:
  ApplicationStop:
    - location: /home/ec2-user/secretsanta/apache-tomcat-9.0.71/bin/shutdown.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: /home/ec2-user/secretsanta/apache-tomcat-9.0.71/bin/startup.sh
      timeout: 60
      runas: root