version: 0.2
phases:
  install:
    runtime-versions:
      java: 1.8.0
  pre_build:
    commands:
      - echo In the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - mv target/secret-santa-service-0.0.1-SNAPSHOT.war secret-santa-service-0.0.1-SNAPSHOT.war
artifacts:
  files:
    - secret-santa-service-0.0.1-SNAPSHOT.war
    - .ebextensions/**/*